FROM ubuntu:24.04

RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y vim nodejs python3 make g++ && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN npm i -y -g nodemon
RUN npm i -y -g ts-node

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY prisma/ prisma/
COPY prisma.config.ts ./
RUN npx prisma generate

EXPOSE 4000

CMD cd /app && npm run server
